import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const lato = Lato({
  weight: ['400', '700'], // Specify desired weights, e.g., regular and bold
  subsets: ['latin'],    // Specify required subsets
  variable: '--font-lato', // Optional: for use with CSS variables
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <body className={cn(
        lato.className,
        "font-bold leading-16"
      )}>
        {children}
      </body>
    </html>
  );
}
